language: ruby
cache: bundler
rvm:
  - 2.1.4
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
addons:
  postgresql: "9.3"
services:
  - redis-server
