language: ruby

sudo: false
cache: bundler
rvm:
  - 2.1.5
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:setup
addons:
  postgresql: "9.3"
services:
  - redis-server
