language: ruby

sudo: false
cache: bundler
rvm:
  - 2.2.2
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:schema:load
addons:
  postgresql: "9.4"
services:
  - redis-server
