#! /bin/sh

case "$1" in
  start)
    echo "Starting mailcatcher"
    /usr/local/rbenv/versions/2.1.5/bin/mailcatcher --ip 0.0.0.0
    exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/mailcatcher {start}"
    exit 1
    ;;
esac

exit 0
